#!/usr/bin/env bash
# migrate-backup.sh — scatter→plugin migration SAFETY FOUNDATION (part of #581)
#
# Three modes:
#   backup               Create a timestamped backup of all at-risk scatter surfaces.
#   restore <backup-dir> Copy backed-up files back to their original locations (revert net).
#   verify  <backup-dir> Re-checksum all backed-up files against the manifest.
#
# Env vars (all have defaults; set to override for non-standard installs):
#   ENGRAM_HOME   defaults to $HOME/.engram
#   CLAUDE_HOME   defaults to $HOME/.claude
#
# Safety invariants:
#   - backup mode is READ-ONLY on all sources — never moves/modifies/deletes them.
#   - Never modifies the ENGRAM graph (knowledge.db, history/, diary/, etc.)
#     in any mode except restore (which only overwrites with a prior backup).
#   - Fail-loud on missing expected sources (WARN + manifest record, never silent skip).
#   - Refuses to run if the backup dir already exists (new timestamp each run).
#   - Checksum-verifies every file immediately after copying.

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve env paths
# ---------------------------------------------------------------------------
ENGRAM_HOME="${ENGRAM_HOME:-$HOME/.engram}"
CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
ts_utc() {
    date -u '+%Y%m%dT%H%M%SZ'
}

sha256_file() {
    # Portable: try sha256sum (Linux), fall back to shasum -a 256 (macOS).
    local f="$1"
    if command -v sha256sum &>/dev/null; then
        sha256sum "$f" | awk '{print $1}'
    elif command -v shasum &>/dev/null; then
        shasum -a 256 "$f" | awk '{print $1}'
    else
        echo "UNAVAILABLE"
    fi
}

file_size() {
    # Portable: stat -c (Linux) vs stat -f (macOS).
    local f="$1"
    if stat --version &>/dev/null; then
        stat -c '%s' "$f"
    else
        stat -f '%z' "$f"
    fi
}

warn() { echo "WARN: $*" >&2; }
info() { echo "INFO: $*"; }
err()  { echo "ERROR: $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# backup — copy all at-risk scatter surfaces to a timestamped directory
# ---------------------------------------------------------------------------
cmd_backup() {
    local backup_root="$HOME/.engram-migration-backups"
    local ts
    ts="$(ts_utc)"
    local backup_dir="$backup_root/$ts"

    if [[ -e "$backup_dir" ]]; then
        err "Backup dir already exists: $backup_dir — refusing to overwrite. (Each run gets a new timestamp.)"
    fi

    mkdir -p "$backup_dir"
    info "Backup dir: $backup_dir"

    # Manifest file (written incrementally, finalised at end).
    local manifest="$backup_dir/manifest.txt"
    {
        echo "# ENGRAM scatter-install migration backup"
        echo "# generated by migrate-backup.sh"
        echo ""
        echo "timestamp:   $ts"
        echo "hostname:    $(hostname)"
        echo "home:        $HOME"
        echo "ENGRAM_HOME: $ENGRAM_HOME"
        echo "CLAUDE_HOME: $CLAUDE_HOME"
        echo ""
        echo "# --- file inventory (path | size_bytes | sha256) ---"
    } > "$manifest"

    # Track any missing-source warnings so we can summarise at the end.
    local warnings=0

    # ------------------------------------------------------------------
    # copy_item <source> <dest_relative_to_backup_dir>
    #   Copies a file or directory tree. Records in manifest.
    #   If source is missing: WARN + record, do not fail.
    # ------------------------------------------------------------------
    copy_item() {
        local src="$1"
        local rel="$2"       # relative path inside backup_dir
        local dst="$backup_dir/$rel"

        if [[ ! -e "$src" ]]; then
            warn "Expected source not found: $src (recorded in manifest)"
            echo "MISSING  $src" >> "$manifest"
            warnings=$((warnings + 1))
            return
        fi

        mkdir -p "$(dirname "$dst")"

        if [[ -d "$src" ]]; then
            # Directory: copy entire tree, then record each file.
            cp -a "$src" "$dst"
            while IFS= read -r -d '' f; do
                local rel_f="${f#$backup_dir/}"
                local sz
                sz="$(file_size "$f")"
                local ck
                ck="$(sha256_file "$f")"
                echo "OK  $sz  $ck  $rel_f" >> "$manifest"
            done < <(find "$dst" -type f -print0)
        else
            # Single file.
            cp -p "$src" "$dst"
            local sz
            sz="$(file_size "$dst")"
            local ck
            ck="$(sha256_file "$dst")"
            echo "OK  $sz  $ck  $rel" >> "$manifest"
        fi
    }

    # ------------------------------------------------------------------
    # 1. $CLAUDE_HOME/settings.json
    # ------------------------------------------------------------------
    copy_item "$CLAUDE_HOME/settings.json" "claude/settings.json"

    # ------------------------------------------------------------------
    # 2. .claude.json — check $CLAUDE_HOME first, fall back to $HOME
    # ------------------------------------------------------------------
    if [[ -f "$CLAUDE_HOME/.claude.json" ]]; then
        copy_item "$CLAUDE_HOME/.claude.json" "claude/.claude.json"
    elif [[ -f "$HOME/.claude.json" ]]; then
        copy_item "$HOME/.claude.json" "home/.claude.json"
        echo "# .claude.json source: $HOME/.claude.json" >> "$manifest"
    else
        warn "Expected .claude.json not found at $CLAUDE_HOME/.claude.json or $HOME/.claude.json (recorded in manifest)"
        echo "MISSING  .claude.json (neither $CLAUDE_HOME/.claude.json nor $HOME/.claude.json)" >> "$manifest"
        warnings=$((warnings + 1))
    fi

    # ------------------------------------------------------------------
    # 3. $CLAUDE_HOME/CLAUDE.md — CRITICAL identity file
    # ------------------------------------------------------------------
    copy_item "$CLAUDE_HOME/CLAUDE.md" "claude/CLAUDE.md"

    # ------------------------------------------------------------------
    # 4. ENGRAM skills: $CLAUDE_HOME/skills/engram-*
    # ------------------------------------------------------------------
    local skill_count=0
    if [[ -d "$CLAUDE_HOME/skills" ]]; then
        while IFS= read -r -d '' skill_dir; do
            local skill_name
            skill_name="$(basename "$skill_dir")"
            copy_item "$skill_dir" "claude/skills/$skill_name"
            skill_count=$((skill_count + 1))
        done < <(find "$CLAUDE_HOME/skills" -maxdepth 1 -type d -name 'engram-*' -print0)
    fi
    if [[ $skill_count -eq 0 ]]; then
        warn "No engram-* skill dirs found under $CLAUDE_HOME/skills"
        echo "MISSING  $CLAUDE_HOME/skills/engram-* (none found)" >> "$manifest"
        warnings=$((warnings + 1))
    fi
    echo "# engram-* skill dirs backed up: $skill_count" >> "$manifest"

    # ------------------------------------------------------------------
    # 5. ENGRAM agents: $CLAUDE_HOME/agents/engram-*
    # ------------------------------------------------------------------
    local agent_count=0
    if [[ -d "$CLAUDE_HOME/agents" ]]; then
        while IFS= read -r -d '' agent_path; do
            local agent_name
            agent_name="$(basename "$agent_path")"
            copy_item "$agent_path" "claude/agents/$agent_name"
            agent_count=$((agent_count + 1))
        done < <(find "$CLAUDE_HOME/agents" -maxdepth 1 \( -type f -o -type d \) -name 'engram-*' -print0)
    fi
    if [[ $agent_count -eq 0 ]]; then
        warn "No engram-* agent files/dirs found under $CLAUDE_HOME/agents"
        echo "MISSING  $CLAUDE_HOME/agents/engram-* (none found)" >> "$manifest"
        warnings=$((warnings + 1))
    fi
    echo "# engram-* agent files/dirs backed up: $agent_count" >> "$manifest"

    # ------------------------------------------------------------------
    # 6. ENGRAM code in ENGRAM_HOME (NOT data):
    #    server.py, engram_*.py, SKILL.md, hooks/, tools/
    # ------------------------------------------------------------------
    copy_item "$ENGRAM_HOME/server.py"    "engram/server.py"
    copy_item "$ENGRAM_HOME/SKILL.md"     "engram/SKILL.md"

    # engram_*.py — individual files (not a tree)
    local py_count=0
    while IFS= read -r -d '' pyf; do
        local pyf_name
        pyf_name="$(basename "$pyf")"
        copy_item "$pyf" "engram/$pyf_name"
        py_count=$((py_count + 1))
    done < <(find "$ENGRAM_HOME" -maxdepth 1 -type f -name 'engram_*.py' -print0)
    if [[ "$py_count" -eq 0 ]]; then warn "No engram_*.py files found under $ENGRAM_HOME"; fi
    echo "# engram_*.py files backed up: $py_count" >> "$manifest"

    # hooks/ and tools/ directories
    copy_item "$ENGRAM_HOME/hooks"  "engram/hooks"
    copy_item "$ENGRAM_HOME/tools"  "engram/tools"

    # ------------------------------------------------------------------
    # 7. config.json — runtime config (multi_agent, cadence, primary_user,
    #    fairy_policy); read-only copy; revert path if migration rewrites
    #    config schema.
    # ------------------------------------------------------------------
    copy_item "$ENGRAM_HOME/config.json" "engram/config.json"

    # ------------------------------------------------------------------
    # 8. knowledge.db (belt-and-suspenders)
    # ------------------------------------------------------------------
    copy_item "$ENGRAM_HOME/knowledge.db" "engram/knowledge.db"

    # ------------------------------------------------------------------
    # Post-copy checksum verification
    # ------------------------------------------------------------------
    info "Verifying post-copy checksums..."
    local verify_failures=0
    while IFS= read -r line; do
        # Lines look like: OK  <size>  <sha256>  <rel_path>
        [[ "$line" =~ ^OK ]] || continue
        local _ok sz ck rel_path
        read -r _ok sz ck rel_path <<< "$line"
        local full_path="$backup_dir/$rel_path"
        if [[ ! -f "$full_path" ]]; then
            warn "Post-copy verify: file missing: $full_path"
            verify_failures=$((verify_failures + 1))
            continue
        fi
        local actual_ck
        actual_ck="$(sha256_file "$full_path")"
        if [[ "$actual_ck" == "UNAVAILABLE" ]]; then
            warn "Post-copy verify: sha256 tool unavailable, skipping checksum for $rel_path"
        elif [[ "$actual_ck" != "$ck" ]]; then
            warn "Post-copy verify: CHECKSUM MISMATCH for $rel_path (expected $ck, got $actual_ck)"
            verify_failures=$((verify_failures + 1))
        fi
    done < "$manifest"

    if [[ $verify_failures -gt 0 ]]; then
        err "Post-copy checksum verification FAILED ($verify_failures mismatch(es)). Backup may be corrupt."
    fi
    info "Post-copy checksums: all OK"

    # ------------------------------------------------------------------
    # Pre-migration STATE snapshot
    # ------------------------------------------------------------------
    {
        echo ""
        echo "# --- pre-migration state snapshot ---"
    } >> "$manifest"

    # Count of ENGRAM hook commands in settings.json.
    # Prefer jq (counts hook entries structurally, no false positives on the
    # literal substring "command" appearing in a hook's command string).
    # Fall back to grep -c '"command"' when jq is absent — less precise but
    # keeps the script functional without a hard dependency on jq.
    if [[ -f "$CLAUDE_HOME/settings.json" ]]; then
        local hook_cmd_count
        if command -v jq &>/dev/null; then
            hook_cmd_count="$(jq '[.. | objects | select(has("command")) | .command] | length' "$CLAUDE_HOME/settings.json" 2>/dev/null || echo 0)"
        else
            hook_cmd_count="$(grep -c '"command"' "$CLAUDE_HOME/settings.json" 2>/dev/null || echo 0)"
        fi
        echo "state.settings_hook_command_count: $hook_cmd_count" >> "$manifest"
    else
        echo "state.settings_hook_command_count: UNAVAILABLE (settings.json missing)" >> "$manifest"
    fi

    # mcpServers names from .claude.json
    local claude_json_path=""
    if [[ -f "$CLAUDE_HOME/.claude.json" ]]; then
        claude_json_path="$CLAUDE_HOME/.claude.json"
    elif [[ -f "$HOME/.claude.json" ]]; then
        claude_json_path="$HOME/.claude.json"
    fi
    if [[ -n "$claude_json_path" ]]; then
        if command -v python3 &>/dev/null; then
            local mcp_names
            mcp_names="$(python3 -c '
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    servers = d.get("mcpServers", {})
    print(" ".join(sorted(servers.keys())))
except Exception as e:
    print("PARSE_ERROR: " + str(e))
' "$claude_json_path" 2>/dev/null || echo "PARSE_ERROR")"
            echo "state.mcpServers_names: $mcp_names" >> "$manifest"
        else
            echo "state.mcpServers_names: UNAVAILABLE (python3 not found)" >> "$manifest"
        fi
    else
        echo "state.mcpServers_names: UNAVAILABLE (.claude.json not found)" >> "$manifest"
    fi

    # Count engram-* skills
    echo "state.engram_skill_count: $skill_count" >> "$manifest"

    # Count engram-* agents
    echo "state.engram_agent_count: $agent_count" >> "$manifest"

    # knowledge.db size
    if [[ -f "$ENGRAM_HOME/knowledge.db" ]]; then
        local db_size
        db_size="$(file_size "$ENGRAM_HOME/knowledge.db")"
        echo "state.knowledge_db_size_bytes: $db_size" >> "$manifest"

        # Node count (if sqlite3 available)
        if command -v sqlite3 &>/dev/null; then
            local node_count
            node_count="$(sqlite3 "$ENGRAM_HOME/knowledge.db" 'SELECT COUNT(*) FROM nodes;' 2>/dev/null || echo "QUERY_FAILED")"
            echo "state.knowledge_db_node_count: $node_count" >> "$manifest"
        else
            echo "state.knowledge_db_node_count: UNAVAILABLE (sqlite3 not installed)" >> "$manifest"
        fi
    else
        echo "state.knowledge_db_size_bytes: UNAVAILABLE (knowledge.db not found)" >> "$manifest"
        echo "state.knowledge_db_node_count: UNAVAILABLE (knowledge.db not found)" >> "$manifest"
    fi

    # ------------------------------------------------------------------
    # Final summary
    # ------------------------------------------------------------------
    echo ""
    info "Backup complete: $backup_dir"
    if [[ $warnings -gt 0 ]]; then
        warn "$warnings source(s) were missing or had issues — see manifest for details."
    fi
    info "Manifest: $backup_dir/manifest.txt"
    info ""
    info "To verify this backup later:   $0 verify $backup_dir"
    info "To restore from this backup:   $0 restore $backup_dir"
}

# ---------------------------------------------------------------------------
# verify <backup-dir> — re-checksum backed-up files against the manifest
# ---------------------------------------------------------------------------
cmd_verify() {
    local backup_dir="${1:-}"
    [[ -n "$backup_dir" ]] || err "Usage: $0 verify <backup-dir>"
    [[ -d "$backup_dir" ]] || err "Backup dir not found: $backup_dir"

    local manifest="$backup_dir/manifest.txt"
    [[ -f "$manifest" ]] || err "manifest.txt not found in: $backup_dir"

    info "Verifying backup: $backup_dir"

    local ok_count=0
    local fail_count=0
    local missing_count=0

    while IFS= read -r line; do
        # OK lines:      OK  <size>  <sha256>  <rel_path>
        # MISSING lines: MISSING  <description>
        if [[ "$line" =~ ^OK[[:space:]] ]]; then
            local _ok sz ck rel_path
            read -r _ok sz ck rel_path <<< "$line"
            local full_path="$backup_dir/$rel_path"

            if [[ ! -f "$full_path" ]]; then
                echo "FAIL (file missing in backup): $rel_path"
                fail_count=$((fail_count + 1))
                continue
            fi

            if [[ "$ck" == "UNAVAILABLE" ]]; then
                echo "SKIP (sha256 was unavailable at backup time): $rel_path"
                ok_count=$((ok_count + 1))
                continue
            fi

            local actual_ck
            actual_ck="$(sha256_file "$full_path")"
            if [[ "$actual_ck" == "UNAVAILABLE" ]]; then
                echo "SKIP (sha256 tool not available now): $rel_path"
                ok_count=$((ok_count + 1))
            elif [[ "$actual_ck" == "$ck" ]]; then
                ok_count=$((ok_count + 1))
            else
                echo "FAIL (checksum mismatch): $rel_path"
                echo "  expected: $ck"
                echo "  actual:   $actual_ck"
                fail_count=$((fail_count + 1))
            fi

        elif [[ "$line" =~ ^MISSING ]]; then
            echo "NOTE (was missing at backup time): ${line#MISSING  }"
            missing_count=$((missing_count + 1))
        fi
    done < "$manifest"

    echo ""
    info "Verify summary: $ok_count OK, $fail_count FAIL, $missing_count originally-missing"

    if [[ $fail_count -gt 0 ]]; then
        err "Verification FAILED — $fail_count file(s) have checksum mismatches or are missing from the backup dir."
    fi

    info "Backup verified OK."
}

# ---------------------------------------------------------------------------
# restore <backup-dir> — copy backed-up files back to original locations
# ---------------------------------------------------------------------------
cmd_restore() {
    local backup_dir="${1:-}"
    [[ -n "$backup_dir" ]] || err "Usage: $0 restore <backup-dir> [--yes]"
    [[ -d "$backup_dir" ]] || err "Backup dir not found: $backup_dir"

    local manifest="$backup_dir/manifest.txt"
    [[ -f "$manifest" ]] || err "manifest.txt not found in: $backup_dir"

    # Accept --yes flag to skip confirmation.
    local yes_flag=0
    for arg in "${@:2}"; do
        [[ "$arg" == "--yes" ]] && yes_flag=1
    done

    # ------------------------------------------------------------------
    # Resolve paths from the manifest (stored at backup time).
    # ------------------------------------------------------------------
    local m_home m_engram_home m_claude_home
    m_home="$(grep '^home:' "$manifest" | awk '{print $2}')"
    m_engram_home="$(grep '^ENGRAM_HOME:' "$manifest" | awk '{print $2}')"
    m_claude_home="$(grep '^CLAUDE_HOME:' "$manifest" | awk '{print $2}')"

    # Fall back to current env if manifest values are empty (shouldn't happen).
    m_home="${m_home:-$HOME}"
    m_engram_home="${m_engram_home:-$ENGRAM_HOME}"
    m_claude_home="${m_claude_home:-$CLAUDE_HOME}"

    echo ""
    echo "Restore plan:"
    echo "  Backup dir:  $backup_dir"
    echo "  ENGRAM_HOME: $m_engram_home"
    echo "  CLAUDE_HOME: $m_claude_home"
    echo ""
    echo "This will overwrite current files in:"
    echo "  $m_claude_home/settings.json"
    echo "  $m_claude_home/CLAUDE.md"
    echo "  $m_claude_home/.claude.json  OR  $m_home/.claude.json"
    echo "  $m_claude_home/skills/engram-*"
    echo "  $m_claude_home/agents/engram-*"
    echo "  $m_engram_home/server.py, engram_*.py, SKILL.md, hooks/, tools/"
    echo "  $m_engram_home/config.json"
    echo "  $m_engram_home/knowledge.db"
    echo ""
    echo "NOTE: directory restores (skills/, agents/, hooks/, tools/) are COMPLETE"
    echo "  REPLACEMENTS — the existing directory is removed (rm -rf) before the"
    echo "  backup copy is written. Contents not in the backup will be lost."
    echo ""

    if [[ $yes_flag -eq 0 ]]; then
        read -r -p "Proceed with restore? [y/N] " confirm
        [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Restore cancelled."; exit 0; }
    fi

    local restored_count=0
    local skipped_count=0

    # ------------------------------------------------------------------
    # restore_item <backed_up_rel_path> <destination>
    # ------------------------------------------------------------------
    restore_item() {
        local rel="$1"
        local dst="$2"
        local src="$backup_dir/$rel"

        if [[ ! -e "$src" ]]; then
            echo "SKIP (not in backup): $rel"
            skipped_count=$((skipped_count + 1))
            return
        fi

        mkdir -p "$(dirname "$dst")"
        if [[ -d "$src" ]]; then
            # For directories, remove current version first to avoid merging.
            rm -rf "$dst"
            cp -a "$src" "$dst"
        else
            cp -p "$src" "$dst"
        fi
        echo "RESTORED: $rel -> $dst"
        restored_count=$((restored_count + 1))
    }

    # Restore settings.json
    restore_item "claude/settings.json"   "$m_claude_home/settings.json"

    # Restore CLAUDE.md
    restore_item "claude/CLAUDE.md"       "$m_claude_home/CLAUDE.md"

    # Restore .claude.json — figure out which slot was backed up
    if [[ -f "$backup_dir/claude/.claude.json" ]]; then
        restore_item "claude/.claude.json"    "$m_claude_home/.claude.json"
    elif [[ -f "$backup_dir/home/.claude.json" ]]; then
        restore_item "home/.claude.json"      "$m_home/.claude.json"
    else
        echo "SKIP (.claude.json not found in backup)"
        skipped_count=$((skipped_count + 1))
    fi

    # Restore engram-* skills (each as its own dir)
    if [[ -d "$backup_dir/claude/skills" ]]; then
        while IFS= read -r -d '' skill_dir; do
            local skill_name
            skill_name="$(basename "$skill_dir")"
            restore_item "claude/skills/$skill_name"   "$m_claude_home/skills/$skill_name"
        done < <(find "$backup_dir/claude/skills" -maxdepth 1 -type d -name 'engram-*' -print0)
    fi

    # Restore engram-* agents
    if [[ -d "$backup_dir/claude/agents" ]]; then
        while IFS= read -r -d '' agent_path; do
            local agent_name
            agent_name="$(basename "$agent_path")"
            # agent_path could be file or dir
            restore_item "claude/agents/$agent_name"   "$m_claude_home/agents/$agent_name"
        done < <(find "$backup_dir/claude/agents" -maxdepth 1 \( -type f -o -type d \) -name 'engram-*' -print0)
    fi

    # Restore ENGRAM_HOME code files
    restore_item "engram/server.py"   "$m_engram_home/server.py"
    restore_item "engram/SKILL.md"    "$m_engram_home/SKILL.md"

    # engram_*.py files
    if [[ -d "$backup_dir/engram" ]]; then
        while IFS= read -r -d '' pyf; do
            local pyf_name
            pyf_name="$(basename "$pyf")"
            restore_item "engram/$pyf_name"   "$m_engram_home/$pyf_name"
        done < <(find "$backup_dir/engram" -maxdepth 1 -type f -name 'engram_*.py' -print0)
    fi

    # hooks/ and tools/ directories
    restore_item "engram/hooks"   "$m_engram_home/hooks"
    restore_item "engram/tools"   "$m_engram_home/tools"

    # config.json
    restore_item "engram/config.json"    "$m_engram_home/config.json"

    # knowledge.db
    restore_item "engram/knowledge.db"   "$m_engram_home/knowledge.db"

    echo ""
    info "Restore complete: $restored_count item(s) restored, $skipped_count skipped."
    echo ""
    echo "IMPORTANT: This script restores config, code, and identity files."
    echo "  '/plugin uninstall engram' is a SEPARATE operator step if you"
    echo "  installed the plugin before reverting — the script cannot do that."
    echo "  After restoring, restart Claude Code / the MCP server to pick up"
    echo "  the restored scatter-install configuration."
}

# ---------------------------------------------------------------------------
# --help / usage
# ---------------------------------------------------------------------------
usage() {
    cat <<EOF
migrate-backup.sh — ENGRAM scatter→plugin migration safety foundation (part of #581)

USAGE:
  $0 backup
        Create a timestamped backup of all at-risk scatter surfaces.
        Backup dir: \$HOME/.engram-migration-backups/<ISO-UTC-timestamp>/
        Read-only on all sources. Fails loud if a source is missing.

  $0 restore <backup-dir> [--yes]
        Copy backed-up files back to their original locations (revert net).
        Prompts for confirmation unless --yes is given.
        Prints a reminder that '/plugin uninstall engram' is a separate step.

  $0 verify <backup-dir>
        Re-checksum each backed-up file against the manifest.
        Exits non-zero if any checksum mismatches or files are missing.

ENVIRONMENT:
  ENGRAM_HOME   ENGRAM data/code dir  (default: \$HOME/.engram)
  CLAUDE_HOME   Claude config dir     (default: \$HOME/.claude)

SAFETY PROPERTIES:
  - backup is read-only on all sources (never moves, modifies, or deletes them).
  - Never modifies the ENGRAM graph (knowledge.db, history/, diary/, etc.) except
    in restore mode (which only writes back a prior backup).
  - Refuses to run backup if the timestamped dir already exists.
  - Checksum-verifies every file immediately after copying.
  - set -euo pipefail throughout.
EOF
    exit 0
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
case "${1:-}" in
    backup)
        cmd_backup
        ;;
    restore)
        cmd_restore "${@:2}"
        ;;
    verify)
        cmd_verify "${@:2}"
        ;;
    --help|-h|help)
        usage
        ;;
    *)
        echo "Usage: $0 {backup|restore <backup-dir>|verify <backup-dir>|--help}" >&2
        exit 1
        ;;
esac
